# Generated by Django 5.0.2 on 2024-03-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_alter_equipo_options_alter_equipo_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
    ]
