# Generated by Django 5.0.2 on 2024-03-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_alter_equipo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicion',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
    ]
